version: '3'

services:
  spring-boot-cache-app:
    image: spring-boot-cache-docker-image
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - 8081:8080
    volumes:
    - "/data/spring-boot-app"